name: Build and Deploy
on:
  push:
    branche: master
jobs:
  Build-And-Deploy:
    run-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v2
          with:
            node-version: '14'
      - run: npm install && npm run build --base-href='EStoryMapFront'
      - run: |
          git config --local user.email "test@chillycheesy.com"
          git config --local user.name "deployBot"
          git add dist/*
          git commit -m "auto deploy front"
      - name: push on gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: gh-pages
